const products = [
  {
    id: 1,
    name: "Mother of Pearl Bracelet",
    price: 999,
    image: "images/p1.jpg",
    category: "healing",
    rating: 4.8,
    reviews: 124,
    badge: "Bestseller",
    description: "Radiate pure calm with our Mother of Pearl Bracelet. Known for its gentle, nurturing energy, this iridescent gem soothes emotional tension, relieves stress, and aligns you with the healing rhythms of the sea. Each bead is hand-polished to reveal its natural luminescence — a timeless piece for the soul in bloom.",
    benefits: ["Emotional Healing", "Stress Relief", "Inner Peace"],
    chakra: "Crown Chakra",
    material: "Genuine Mother of Pearl, Gold-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 2,
    name: "Citrine Bracelet",
    price: 849,
    image: "images/p2.jpg",
    category: "wealth",
    rating: 4.9,
    reviews: 98,
    badge: "Top Rated",
    description: "Welcome abundance with the golden glow of Citrine. Called the 'Merchant's Stone', this sun-kissed crystal amplifies prosperity, confidence, and creative energy. Wear it to attract financial success and ignite your inner fire. A must-have for entrepreneurs and dreamers alike.",
    benefits: ["Abundance Magnet", "Confidence Boost", "Creative Energy"],
    chakra: "Solar Plexus Chakra",
    material: "Natural Citrine Quartz, Sterling Silver clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 3,
    name: "Labradorite Bracelet",
    price: 799,
    image: "images/p3.jpg",
    category: "protection",
    rating: 4.7,
    reviews: 76,
    badge: "Premium",
    description: "A stone of transformation and magic, Labradorite shields your aura from negative energies while awakening your intuition. Its stunning spectral play of colors — shifting blues, greens, and golds — mirrors the depth of your inner universe. Ideal for those on a spiritual journey.",
    benefits: ["Aura Shield", "Intuition Awakening", "Transformation"],
    chakra: "Third Eye Chakra",
    material: "Natural Labradorite, Gold-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 4,
    name: "Bloodstone Bracelet",
    price: 649,
    image: "images/p4.jpg",
    category: "healing",
    rating: 4.6,
    reviews: 55,
    badge: null,
    description: "Ancient warriors wore Bloodstone for courage and vitality. This deep green stone flecked with crimson revitalizes your energy, supports physical stamina, and encourages emotional resilience. It grounds your spirit while empowering your will to overcome challenges.",
    benefits: ["Vitality Boost", "Courage & Strength", "Grounding Energy"],
    chakra: "Root Chakra",
    material: "Genuine Bloodstone, Stainless Steel clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 5,
    name: "Moonstone Bracelet",
    price: 849,
    image: "images/p5.jpg",
    category: "love",
    rating: 4.9,
    reviews: 143,
    badge: "Bestseller",
    description: "Moonstone, the stone of new beginnings, reflects the light of the moon within every bead. It nurtures deep emotional connection, amplifies feminine energy, and guides you through life's transitions with grace. A divine gift for self-love, new romance, and spiritual awakening.",
    benefits: ["New Beginnings", "Emotional Balance", "Feminine Energy"],
    chakra: "Heart & Crown Chakra",
    material: "Genuine Rainbow Moonstone, Rose Gold clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 6,
    name: "Green Aventurine Bracelet",
    price: 649,
    image: "images/p6.jpg",
    category: "wealth",
    rating: 4.5,
    reviews: 89,
    badge: null,
    description: "Known as the 'Stone of Opportunity', Green Aventurine is the luckiest of all crystals — especially in manifesting prosperity and wealth. It aligns conditions so opportunity is inevitable. Release old patterns and embrace growth, abundance, and optimism with every wear.",
    benefits: ["Lucky Charm", "Opportunity Magnet", "Financial Growth"],
    chakra: "Heart Chakra",
    material: "Natural Green Aventurine, Gold-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 7,
    name: "Rose quartz Bracelet",
    price: 649,
    image: "images/p7.jpg",
    category: "love",
    rating: 4.9,
    reviews: 201,
    badge: "Top Rated",
    description: "Our signature Love & Harmony Bracelet combines Rose Quartz, Rhodonite, and Morganite — three of the most powerful love stones — into a single, breathtaking piece. Open your heart chakra, attract soulful connections, and deepen existing bonds. The ultimate gift for the one you love.",
    benefits: ["Unconditional Love", "Relationship Harmony", "Heart Opening"],
    chakra: "Heart Chakra",
    material: "Rose Quartz, Rhodonite, Morganite, Rose Gold clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 8,
    name: "Success & Wealth Bracelet",
    price: 699,
    image: "images/p8.jpg",
    category: "wealth",
    rating: 4.8,
    reviews: 167,
    badge: "Premium",
    description: "Our most powerful wealth bracelet combines Pyrite, Tiger Eye, and Citrine in one statement piece. Pyrite attracts gold-level success, Tiger Eye brings unwavering focus, and Citrine amplifies abundance energy. Wear it during important meetings, negotiations, or whenever you need that winning edge.",
    benefits: ["Wealth Attraction", "Success Mindset", "Laser Focus"],
    chakra: "Solar Plexus & Sacral Chakra",
    material: "Pyrite, Tiger Eye, Citrine, 18K Gold-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 9,
    name: "Tiger Eye Bracelet",
    price: 649,
    image: "images/p9.jpg",
    category: "protection",
    rating: 4.6,
    reviews: 112,
    badge: null,
    description: "The Tiger Eye bracelet is your personal shield and power booster. It combines the earth's grounding energy with the sun's fierce vitality, creating a stone that protects from negative energies while supercharging your confidence and willpower. A warrior's amulet for the modern world.",
    benefits: ["Personal Power", "Protection Shield", "Mental Clarity"],
    chakra: "Sacral & Solar Plexus",
    material: "Natural Tiger Eye, Stainless Steel clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 10,
    name: "Red Jasper Bracelet",
    price: 699,
    image: "images/p10.jpg",
    category: "healing",
    rating: 4.4,
    reviews: 63,
    badge: "Value Pick",
    description: "Red Jasper is the stone of endurance — a gentle but powerful grounding stone that stimulates your life force and passion. It boosts physical energy, supports detoxification, and helps you stay rooted in the present moment. Perfect for those rebuilding strength after challenges.",
    benefits: ["Life Force Energy", "Physical Stamina", "Emotional Grounding"],
    chakra: "Root Chakra",
    material: "Genuine Red Jasper, Stainless Steel clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 11,
    name: "Amethyst Bracelet",
    price: 799,
    image: "images/p11.jpg",
    category: "healing",
    rating: 4.8,
    reviews: 189,
    badge: "Bestseller",
    description: "Amethyst, the stone of peace and higher consciousness, calms an overactive mind, enhances meditation, and promotes restful sleep. Its violet hue carries a frequency of divine protection and spiritual wisdom. Wear it to quiet mental chatter and connect with your higher self.",
    benefits: ["Deep Calm", "Meditation Aid", "Sleep Enhancement"],
    chakra: "Crown & Third Eye Chakra",
    material: "Natural Amethyst, Silver-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 12,
    name: "Turquoise Bracelet",
    price: 699,
    image: "images/p12.jpg",
    category: "protection",
    rating: 4.7,
    reviews: 94,
    badge: null,
    description: "Revered by ancient civilizations as a sacred protective talisman, Turquoise absorbs negative energies and shields its wearer from harm. It also enhances communication, encourages truth-telling, and brings a profound sense of calm and wholeness. A timeless crystal for those who travel and explore.",
    benefits: ["Sacred Protection", "Communication", "Wholeness"],
    chakra: "Throat Chakra",
    material: "Genuine Turquoise, Gold-plated clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 13,
    name: "Black Tourmaline Bracelet",
    price: 699,
    image: "images/p13.jpg",
    category: "protection",
    rating: 4.9,
    reviews: 231,
    badge: "Top Rated",
    description: "The most powerful protection crystal in existence, Black Tourmaline creates an impenetrable shield around your aura, deflecting negative energies, EMF radiation, and psychic attacks. It anchors you to the earth and transmutes fear into strength. For those who need a spiritual bodyguard.",
    benefits: ["Ultimate Protection", "EMF Shield", "Fear Transmutation"],
    chakra: "Root Chakra",
    material: "Natural Black Tourmaline, Matte Black clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 14,
    name: "Smokey Quartz Bracelet",
    price: 799,
    image: "images/p14.jpg",
    category: "healing",
    rating: 4.6,
    reviews: 77,
    badge: null,
    description: "Smokey Quartz is the ultimate antidote to stress and negativity. Its gentle, grounding energy neutralizes negative vibrations, detoxifies your emotional field, and relieves anxiety. It teaches you to release what no longer serves you, making room for lightness, clarity, and healing.",
    benefits: ["Stress Neutralizer", "Emotional Detox", "Anxiety Relief"],
    chakra: "Root Chakra",
    material: "Natural Smokey Quartz, Antique Silver clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 15,
    name: "Rhodonite Bracelet",
    price: 649,
    image: "images/p15.jpg",
    category: "love",
    rating: 4.7,
    reviews: 108,
    badge: null,
    description: "Rhodonite is the stone of compassion — it clears away emotional wounds, self-doubt, and old heartbreak, replacing them with forgiveness and self-love. Its rosy pink hues carry a frequency of nurturing strength. Wear it to heal your heart and rediscover your capacity for deep, authentic love.",
    benefits: ["Heart Healing", "Self-Love", "Forgiveness"],
    chakra: "Heart Chakra",
    material: "Genuine Rhodonite, Rose Gold clasp",
    size: "Adjustable 16–20cm"
  },
  {
    id: 16,
    name: "Hematite bracelet",
    price: 599,
    image: "images/Hematite bracelet benefits infographic.png",
    category: "protection",
    rating: 4.6,
    reviews: 95,
    badge: null,
    description: "Hematite is the stone of grounding — it absorbs negative energy and promotes strength, focus, and stability.",
    benefits: ["Grounding", "Protection", "Mental Clarity"],
    chakra: "Root Chakra",
    material: "Genuine Hematite, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 17,
    name: "Howlite Bracelet",
    price: 649,
    image: "images/Howlite bracelet benefits and properties.png",
    category: "calm",
    rating: 4.5,
    reviews: 82,
    badge: null,
    description: "Howlite is the stone of calmness — it soothes the mind, reduces stress, and promotes emotional balance and patience.",
    benefits: ["Calm & Stress Relief", "Patience", "Emotional Balance"],
    chakra: "Crown Chakra",
    material: "Genuine Howlite, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 18,
    name: "Selenite Bracelet",
    price: 649,
    image: "images/Selenite bracelet with calming benefits.png",
    category: "healing",
    rating: 4.7,
    reviews: 88,
    badge: null,
    description: "Selenite is the stone of clarity — it cleanses negative energy, promotes mental clarity, and brings deep inner peace.",
    benefits: ["Mental Clarity", "Energy Cleansing", "Inner Peace"],
    chakra: "Crown Chakra",
    material: "Genuine Selenite, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 19,
    name: "South African Turquoise Bracelet",
    price: 749,
    image: "images/South African turquoise wellness guide.png",
    category: "healing",
    rating: 4.6,
    reviews: 76,
    badge: null,
    description: "South African Turquoise is the stone of transformation — it supports personal growth, provides protection, and encourages emotional healing.",
    benefits: ["Emotional Healing", "Protection", "Growth & Transformation"],
    chakra: "Heart Chakra",
    material: "Genuine South African Turquoise, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 20,
    name: "Green Jade Bracelet",
    price: 699,
    image: "images/South Green Jade bracelet benefits.png",
    category: "wealth",
    rating: 4.8,
    reviews: 92,
    badge: null,
    description: "South Green Jade is the stone of prosperity — it attracts good fortune, offers protection, and brings emotional balance and inner peace.",
    benefits: ["Good Fortune", "Protection", "Emotional Balance", "Inner Peace"],
    chakra: "Heart Chakra",
    material: "Genuine South Green Jade, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 21,
    name: "Pyrite Bracelet",
    price: 699,
    image: "images/Pyrite bracelet with maroon text design.png",
    category: "wealth",
    rating: 4.7,
    reviews: 84,
    badge: null,
    description: "Pyrite is the stone of abundance - it attracts wealth, boosts confidence, and protects against negative energy.",
    benefits: ["Abundance", "Protection", "Willpower"],
    chakra: "Solar Plexus Chakra",
    material: "Genuine Pyrite, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 22,
    name: "Sunstone Bracelet",
    price: 799,
    image: "images/Sunstone bracelet with empowering benefits.png",
    category: "healing",
    rating: 4.7,
    reviews: 79,
    badge: null,
    description: "Sunstone is the stone of joy — it uplifts mood, boosts confidence, and brings positivity, energy, and personal power.",
    benefits: ["Joy", "Confidence", "Empowerment", "Vitality"],
    chakra: "Sacral Chakra",
    material: "Genuine Sunstone, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 23,
    name: "Sulemani Hakik Bracelet",
    price: 699,
    image: "images/Sulemani bracelet with benefits listed (1).png",
    category: "protection",
    rating: 4.6,
    reviews: 74,
    badge: null,
    description: "Sulemani Hakik is the stone of protection — it shields against negative energy, enhances inner strength, and promotes grounding and focus.",
    benefits: ["Protection", "Strength", "Grounding", "Focus"],
    chakra: "Root Chakra",
    material: "Genuine Sulemani Hakik (Black Agate), Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 24,
    name: "Gold Hematite Bracelet",
    price: 799,
    image: "images/Gold Hematite bracelet with benefits.png",
    category: "protection",
    rating: 4.7,
    reviews: 81,
    badge: "Trending",
    description: "Gold Hematite is the stone of strength — it boosts confidence, provides protection, and brings balance and stability to the mind and body.",
    benefits: ["Confidence", "Protection", "Strength", "Balance"],
    chakra: "Root Chakra",
    material: "Gold Plated Hematite, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 25,
    name: "Money Magnet Bracelet",
    price: 649,
    image: "images/Money Magnet bracelet with jade and gold.png",
    category: "combo",
    rating: 4.9,
    reviews: 112,
    badge: "Best Seller",
    description: "The Money Magnet bracelet combines powerful stones to attract wealth, success, and protection — helping you stay focused, confident, and financially aligned.",
    benefits: ["Wealth", "Success", "Protection", "Balance"],
    chakra: "Solar Plexus Chakra",
    material: "Pyrite & Green Jade Combo, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 26,
    name: "Triple Protection Bracelet",
    price: 699,
    image: "images/Triple Protection beaded bracelet display.png",
    category: "combo",
    rating: 4.9,
    reviews: 97,
    badge: "Best Seller",
    description: "The Triple Protection bracelet combines powerful stones to shield against negative energy, enhance inner strength, and provide grounding and stability in everyday life.",
    benefits: ["Protection", "Strength", "Grounding", "Balance"],
    chakra: "Root Chakra",
    material: "Tiger Eye, Hematite & Sulemani Hakik Combo, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 27,
    name: "Rose Quartz & Howlite Bracelet",
    price: 699,
    image: "images/Rose quartz and howlite bracelet benefits.png",
    category: "combo",
    rating: 4.8,
    reviews: 89,
    badge: "Trending",
    description: "This calming combo of Rose Quartz and Howlite promotes love, emotional healing, and inner peace — helping you stay balanced, relaxed, and connected to your heart.",
    benefits: ["Love", "Healing", "Calm", "Balance"],
    chakra: "Heart Chakra",
    material: "Rose Quartz & Howlite Combo, Elastic Cord",
    size: "Adjustable 16-20cm"
  },
  {
    id: 28,
    name: "7 Chakra Bracelet",
    price: 799,
    image: "images/Chakra bracelet wellness flatlay design.png",
    category: "combo",
    rating: 4.9,
    reviews: 120,
    badge: "Best Seller",
    description: "The 7 Chakra bracelet is designed to balance and align all energy centers — promoting harmony, positivity, and spiritual growth in mind, body, and soul.",
    benefits: ["Balance", "Spiritual Growth", "Positive Energy", "Healing"],
    chakra: "All Chakras",
    material: "Multi-Stone Chakra Beads, Elastic Cord",
    size: "Adjustable 16-20cm"
  }
];
